name: Show Server Time

on:
  schedule:
    # Runs every 2 minutes
    - cron: "*/2 * * * *"

jobs:
  show-time:
    runs-on: ubuntu-latest
    steps:
      # Check the server time
      - name: Display server time
        run: | 
          echo "Current server time: $(date)"
